### ISSUE TITLE
Module 3: Code contributions Subsection

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#15]
**Milestone:** Contrubutions

**Description**
Creating the content for the "Code contributions" subsection.

**Sub-tasks**
- [x]  "Contributing Code" unit
- [x]  "Architecture" unit
- [x]  "Overview of Contribution Paths" unit

**Definition of Done**
The initial version of the "Code contributions" subsection is published.

**Comment by sarina** [comment]
@mariajgrimaldi @jalondonot [this section](https://training.openedx.org/courses/course-v1:Axim+Open-edX-Intro+2023/courseware/593f0b01bbc84e3ebc1871d0c0157b48/4f57f384922b43cf9d9fd1522087d2f7/3?activate_block_id=block-v1%3AAxim%2BOpen-edX-Intro%2B2023%2Btype%40vertical%2Bblock%4094c485088c794d8397b766f83d3f12af) is ready for review.

**Comment by mariajgrimaldi** [comment]
What do you think about adding a brief description before the key takeaways:
Here are some quick notes about what you'll find in this section. It'd be useful to read it before checking the architecture video, so you can research the technologies beforehand!

**Comment by mariajgrimaldi** [comment]
[out of curiosity] why is the OEP description and ADR in different subsections? 

OEP is part of the Getting help section while ADR is part of the code contributions -- both can be used as references. I see an OEP as a very technical document although, as you mentioned, it can contain documentation outside the Open edX codebase. So I wonder... should we change the section to: Technical documents and include ADRs? Then, in code resources we just mention ADRs like we're doing with OEPs.

It could be something like this:

### Technical documents

When searching for answers about community processes or architecture design documents, the best documents to look for are Open edX Proposals or ADRs.

_Description of each_

Then in coding resources, we add ADRs to the list of references.

Or do you think that would be confusing somehow?

**Comment by sarina** [comment]
> Here are some quick notes about what you'll find in this section. Reading it before checking the architecture video would be helpful so you can research the technologies we use beforehand!

This is good text, I added it.

> [out of curiosity] why is the OEP description and ADR in different subsections?


I mention the OEPs in Module 2, Getting Help because there are a few that are non-technical and we already mentioned the Product Core OEP.  It is clearly stated that many are technical, but some are broadly relevant:

> Some OEPs cover the processes by which our community operates: we have ones for Core Contributors, one for Maintainers, and one for the Core Product. Others are more technical in nature, meant for those who are coding Open edX software.

We, as a community, often mention OEPs and I think it's good that everyone knows what that means. However, ADRs are _purely_ technical and don't belong in the general Getting Help section that's aimed at everyone. 

In Module 3, Code Contributions, OEP site is given as a reference in the resources unit. And then, ADRs are also explained. I don't think OEPs need to be explained twice, and I don't think ADR explanation belongs in the place that is general use.

<img width="547" alt="Screenshot 2023-05-24 at 14 52 23" src="https://github.com/openedx/training-courses/assets/1985317/e20ea961-7204-4583-b59a-d820259f1d51">
