### ISSUE TITLE
Feedback round for cc course

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#19]
- [ ] Identify reviewers
- [ ] Send course out for review
- [ ] Collect & respond to feedback

**Comment by sarina** [comment]
So far have asked @mariajgrimaldi & @jalondonot to provide a first round of review. I am looking for overall feedback on structure, feedback on the text and exercises, and suggestions to make the course a little bit more exciting (well, less boring)... maybe suggestions for pictures and other visual things?

**Comment by DeanJayMathew** [comment]
@sarina is the draft course live in an Open edX instance somewhere already?

**Comment by sarina** [comment]
@DeanJayMathew there is a draft course, it's not publicly available. I'll send you the information.

**Comment by jalondonot** [comment]
Hi @sarina, great job so far! after reviewing the course, I found the content and its length totally appropriate for what I would expect from a course like this. Being a rabbit hole should be the first objective we should aim for with these courses. Of course, they should include enough information to let the newcomer start contributing, but also, they must have catchy, short, and interesting content.

For now, I just have two comments to add to what Majo already said:

- The ["How to Become an Open edX Core Contributor" video](https://training.openedx.org/courses/course-v1:tCRIL+CC101+2022/courseware/697e93419a6049f081574db2313cdde4/8f9b447f5c2a47c3af4f8dc2e4bd04f1/?child=last) could add valuable context, but we should not rely on it as a key source of information, since it is too long and, in my opinion, most of the students would just watch the first 5 minutes of it. Let's make sure the information that is provided there can be found in other sections or references included in the course.
- I couldn't find any references to the process to be followed to become a core contributor.
- The Architecture Coordination wg is missing in the ["Working Groups" section](https://training.openedx.org/courses/course-v1:tCRIL+CC101+2022/courseware/760a4a358d85409d9e67a9e8ee8d346e/7f64dcf1479d41b88a12fe71aa220003/?activate_block_id=block-v1%3AtCRIL%2BCC101%2B2022%2Btype%40sequential%2Bblock%407f64dcf1479d41b88a12fe71aa220003)

Hope this can help :)

**Comment by sarina** [comment]
Hi! Thanks for the feedback, I am incorporating it now. @jalondonot a few responses:

> The ["How to Become an Open edX Core Contributor" video](https://training.openedx.org/courses/course-v1:tCRIL+CC101+2022/courseware/697e93419a6049f081574db2313cdde4/8f9b447f5c2a47c3af4f8dc2e4bd04f1/?child=last) could add valuable context, but we should not rely on it as a key source of information

Agree. I played with that in a supplemental section. I'll add that back to an "optional" section and make the info you need to have short and sweet.

> I couldn't find any references to the process to be followed to become a core contributor.

Correct. This course is aimed specifically at people who have already been elected a Core Contributor. "How to become a Core Contributor" is a different course. It is possibly just a section in a general Onboarding course.

**Comment by sarina** [comment]
@mariajgrimaldi I followed most of your feedback:

> At the end of the course, we could add a few takeaways for each section, so it's easier to remember and revisit in case needed. Also, at least for me, it's exciting enough!

I like this idea, but it's hard to summarize your own work. If you wanted to take a crack at providing me text, I'd really appreciate it.

> Maybe I'd summarize sections like Roles Overview and Working Groups with enough info to get the gist. That would be enough since there's detailed information on them in Confluence, so if the contributor thinks it's missing more details, then they could check the Confluence page.

Good point. I decided for each section, I'd use 3 examples and then link to the wiki pages.

> Should we have a section like [this](https://training.openedx.org/courses/course-v1:tCRIL+CC101+2022/courseware/81c2f5b25048477a88f0d71307f2adf0/746b9f582b59495db108cff702e78eb8/?child=first) for non-code contributors? Like check access to transifex or the marketing site, etc

I didn't think so, but when I started writing it I realize we should! So I've added that.

> After getting some feedback from newcomers, we could add a FAQ! Or if you have a set of those, we could add it to the course now :)

I don't have any FAQ yet. I've put in feedback Google forms (iframe'd in) so we can start collecting that info.

**Comment by mariajgrimaldi** [comment]
@sarina: I'll help you with the takeaways of course! ❤️

**Comment by sarina** [comment]
@mariajgrimaldi I made a takeaways section! Please feel free to edit it! https://training.openedx.org/courses/course-v1:tCRIL+CC101+2022/courseware/35f46aa47d5c47f1ba107042d1243c80/79157ac2a2cf4d3884873ef981147fe6/?activate_block_id=block-v1%3AtCRIL%2BCC101%2B2022%2Btype%40sequential%2Bblock%4079157ac2a2cf4d3884873ef981147fe6
