### ISSUE TITLE
Intro to the Open edX Project course feedback

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#46]
Reviewers:

- [ ] @gabrieldamours 
- [ ] @sambapete

 I’d love feedback on where we could use graphics, videos, and/or assessments to make the course more engaging.

**Comment by sambapete** [comment]
In About this Course > Who should take this course?

**Comment by sambapete** [comment]
Nitpicking at this point. The footer still refers to "presented by The Center for Reimagining Learning (tCRIL)"

**Comment by sambapete** [comment]
In **"Module 1 - The Open edX project > About the Open edX Project > Open edX Project Today"**

Should we include a link to an explanation of the Maintainer Role and Program?

**Comment by sambapete** [comment]
In **"Module 1 - The Open edX project > About the Open edX Project > Major Community Members"**

Reusing [1] 3 times. The last two should probably be [4] and [5]

The first [1] links to a Page Not Found.

**Comment by sambapete** [comment]
Still in the nitpicking category. Mixed use of "Open source" and "Open Source".

**Comment by sambapete** [comment]
Overall, a very good introduction to the many aspects of the project and the community. Short and sweet.

I wish I had someone internally who is not as familiar to the project as I am and that could review the course. I might be too biased. And @gabrieldamours might have the same issue since he was working for one of our partner at EDUlib before joining OpenCraft. We definitely need a newbie to crash-test the course.

**Comment by sarina** [comment]
@sambapete thanks for your comments! I have addressed them all. I think they were good. I agree with the `[ref]` notation - I don't like it in the context of an online webpage. I'm going to download the course and search for other instances of that, as well as non- "Open Source" capitalizations.

**Comment by mariajgrimaldi** [comment]
I asked another new teammate -- non-technical this time -- for a review as well. I hope we can get that soon! 

Thank you so much @sambapete!

**Comment by sarina** [comment]
@mariajgrimaldi @gabrieldamours I plan to release the course next Tuesday (30 May), so please provide your feedback by Thursday this week (25 May).

**Comment by gabrieldamours** [comment]
Pierre covered a lot of ground here -- thanks a lot! Here's my remaining feedback/suggestions, and don't hesitate to take this with a grain of salt ; )

- The" Who should take this course" unit should be renamed to something like "Why take this course", because that's roughly what the unit explains.
- There _should_ be a new unit called "Who should take this course" that briefly describes the target learners. This should also help answer the question "do I need to know how to code to contribute to the Open edX platform?".
- Potential contributors need to know quickly how they can help out. If I'm already familiar with the project and want to skip to the part where we can learn about how to contribute, maybe we can add a link in the intro section that leads directly to Module 3?
- In the first unit of Module 3, it would be helpful to briefly describe what's it like being a CC, and what types of tasks are involved.
- We should add a subsection in Module 3 that describes the core contributor sprint process and schedule, so that potential contributors understand and adhere to the process.

**Comment by sarina** [comment]
@gabrieldamours I addressed your first two points:



![Image](https://github.com/openedx/training-courses/assets/1985317/2e21d69d-13c7-48b5-862e-5abd86022349)

And I added a note about Core Contributor sprints. I don't think at the beginning of their journey it is appropriate to ask them to do their own work in 2 week chunks - that's a large and unnecessary expectation at this point.



![Image](https://github.com/openedx/training-courses/assets/1985317/9ec52824-2d94-4e03-942f-65f0cdb99e87)


Can you reply to my questions in my previous comment, or close the ticket if you're satisfied?

**Comment by gabrieldamours** [comment]
Thanks for the nice additions, @sarina. For the pending points:

`I hesitated adding links to modules from the intro section, because you get that already when you land on the course page`

Right, I also think it's fine to leave as-is. 

`What text would you suggest to "briefly describe what it's like being a CC"?`

After giving this some thought and reviewing the course materials, it feels to me like the various units give a good idea of what the task looks like -- so I'm withdrawing my suggestion.

This looks great all-around, kudos for making this great course! I'll close the ticket as suggested.
